name: Python Setup with WebDriver and Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install from requirements.txt

      - name: Install WebDriver and ChromeDriver
        run: |
          pip install webdriver-manager chromedriver-autoinstaller

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run the mailer
        env:
          SOME_SUPER_SECRET: ${{ secrets.SOME_SUPER_SECRET }}
        run: |
          if [ -z "$SOME_SUPER_SECRET" ]; then
            echo "❌ Secret is empty"
          else
            echo "✅ Secret is set and has length ${#SOME_SUPER_SECRET}"
          fi
